### ISSUE TITLE
Hey, I don't know if this is the right way to do this but I get an error when I run "node index.js" in my VSC terminal and I don't know how to fix it!

### ISSUE THREAD

**Issue by Ethdev69** [HashLips/generative-art-node#1]
![error node index js](https://user-images.githubusercontent.com/89483626/130678672-e4c16d70-d983-4be6-83a5-08a995ace2bc.png)

If anyone would know what I did wrong pls tell me, I just copied most of the code so I don't know what caused the error. I have been trying to fix it myself but it doesn't work

**Comment by HashLips** [comment]
You need to run npm install first

**Comment by Ethdev69** [comment]
Omg thank you soo much, it worked and now I am getting the outputs!!! I can't thank you enough man, I was really struggeling and I knew there had to be an easy solution
