### ISSUE TITLE
startEditionAt

### ISSUE THREAD

**Issue by wibletcodes** [HashLips/generative-art-node#100]
Hey I'm just really having trouble, everything seems to be fine when generating my project but I've been working on a bit of a complicated one. its not just one base so I can't just generate 10000 different combinations. With 5 different bases I've had to do them all separately and one problem I've found is that each time I generate these separately, they start from 1, is there any code that I can put into here that will allow me to start the edition at a certain number out of the 10000?

**Comment by doudoubird** [comment]
I am looking for the same thing...I tried changing const startEditionFrom but it throws an error: TypeError: Cannot read property 'layers' of undefined
