### ISSUE TITLE
Cannot run npm run build

### ISSUE THREAD

**Issue by Bouchwari** [HashLips/generative-art-node#110]
I have tried on windows but in the end, I keep getting the same message i.e. cannot find the directory and it always refers to "layers/ball" but I have already changed the layers and there is no ball layer.

Thanks 
![Screenshot 2021-11-25 210002](https://user-images.githubusercontent.com/62405900/143499458-f637b3cd-9326-485a-837a-8e86350b6631.png)

**Comment by Nousnouss** [comment]
I had the same isuue, you just forgot to save the changes you made, save , refresh and it will normally works ;)
Peace, Love and caféine !

**Comment by Bouchwari** [comment]
> I had the same isuue, you just forgot to save the changes you made, save , refresh and it will normally works ;) Peace, Love and caféine !

Thank you so much for your help it's right I forgot to save the changes it works perfectly again thank also special thanks to the developer.
