### ISSUE TITLE
Error Code when trying to upload NFTs to IPFS node.js

### ISSUE THREAD

**Issue by nothingatall200** [HashLips/generative-art-node#133]
I have a problem... I get the following error codes:

error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:ReferenceError: basepath is not defined

This is my upload code...

const FormData = require('form-data');
const fetch = require('node-fetch');
const path = require('path')
const basePath = process.cwd();
const fs = require("fs");

fs.readdirSync(`${basePath}/build/images`).forEach((file) => {
    const formData = new FormData();
    const fileStream = fs.createReadStream(`${basePath}/build/images/${file}`);
    formData.append("file", fileStream);

let url = 'https://api.nftport.xyz/v0/files';

let options = {
  method: "POST",
  headers: {
    Authorization: 'xy',
  },
  body: formData
};

fetch(url, options)
  .then((res) => res.json())
  .then((json) => {
      const fileName = path.parse(json.file_name).name;
      let rawdata = fs.readFileSync(`${basepath}/build/json/$
      {fileName}.json`);
      let metaData = JSON.parse(rawdata);

      metaData.file_url = json.ipfs_url;
      
      fs.writeFileSync(`${basepath}/build/json/${fileName}.json`,
      JSON.stringify(metaData, null, 2));

      console.log(`${json.file_name} uploaded & ${fileName}.json 
      updated!`);
  })
  
  .catch((err) => console.error("error:" + err));
});

**Comment by LilT-Boy** [comment]
If you found a solution you can ignore that. If not, just take that new code from codeStackr and put in your API Key: https://github.com/codeSTACKr/video-source-code-create-nft-collection/blob/main/utils/nftport/uploadFiles.js

**Comment by nothingatall200** [comment]
Solved! Thanks

**Comment by freemasonrysquared** [comment]
> Solved! Thanks

How did you solve this issue. I have it also.

**Comment by Abudihaymour** [comment]
> Solved! Thanks

How did you solve this issue. I have it also.

**Comment by ghost** [comment]
i also facing the issue during upload on ipfs.
