### ISSUE TITLE
Transparent layers ignored

### ISSUE THREAD

**Issue by enalneimad** [HashLips/generative-art-node#134]
Hi,

When I add a transparent layer as a background and call it 'blank' for eg, the layer is ignored & random background colors are generated instead. I tried to get a response in telegram & discord with no response. Greatly appreciate a solution to this issue, cheers.

**Comment by alfreddagenais** [comment]
Hum I'm not sure to understand all your problem. They are missing some information for me to correctly understand.

But I think my PR should solve the transparent issues you mentioned : https://github.com/HashLips/generative-art-node/pull/145

**Comment by nikojay** [comment]
Solution:
Change generate: true
to generate: false
![1645870524532796478155359935131](https://user-images.githubusercontent.com/100468793/155839360-18eea99e-45a3-41de-8013-03994876bc26.jpg)

**Comment by enalneimad** [comment]
Many thanks.

I'd given up on a solution. Just about to do a rerun as well, so perfect timing. I was going to create a batch action to remove the bg's in Photoshop. No need now, very much appreciated.
