### ISSUE TITLE
If I generate more then 5 editions, it says killed and the program stops

### ISSUE THREAD

**Issue by Losh531** [HashLips/generative-art-node#14]
Title says all!

**Comment by groveep** [comment]
I am having this same issue. trying to generate 10k unique pieces and will get to like 1230 and my terminal displays

`zsh: killed node index.js`

**Comment by sshahbaz47** [comment]
![Generate issue](https://user-images.githubusercontent.com/87954883/131867887-190ee77c-caad-48d2-b372-45772e0feaa8.PNG)

I also have a similar issue expect I cant generate more then 5 images even if I change the "const defaultEdition = 15;" to 15.

**Comment by jacklau04** [comment]
yea how can you fix that?

**Comment by CiaranPearse** [comment]
Do you have enough files to generate the editions you want. If you have 2 layers with 5 items in each then you can only generate 25 editions.

**Comment by Losh531** [comment]
Turns out the problem is that the computer just couldn't handle any more then that.
