### ISSUE TITLE
SOLVED: CATCH ERROR: FetchError: request to https://api.nftport.xyz/v0/files failed, reason: socket hang up

### ISSUE THREAD

**Issue by tim9609** [HashLips/generative-art-node#165]
hey,
I watched the video "https://www.youtube.com/watch?v=cLB7u0KQFIs" as an orientation to release my NFT collection. But, when I am at the step "Upload Images and Metadata to IPFS" and enter npm run upload_files in the terminal, I get the error "CATCH ERROR: FetchError: request to https://api.nftport.xyz/v0/files failed, reason: socket hang up". This means that the images are not uploaded to IPFS. Does anyone have a solution. Thanks in advance!

const FormData = require("form-data");
const path = require("path");
const basePath = process.cwd();
const fs = require("fs");

const { RateLimit } = require('async-sema');
const { fetchWithRetry } = require(`${basePath}/utils/functions/fetchWithRetry.js`);

const { LIMIT } = require(`${basePath}/src/config.js`);
const _limit = RateLimit(LIMIT);

const allMetadata = [];
const regex = new RegExp("^([0-9]+).png");

async function main() {
  console.log("Starting upload of images...");
  const files = fs.readdirSync(`${basePath}/build/images`);
  files.sort(function(a, b){
    return a.split(".")[0] - b.split(".")[0];
  });
  for (const file of files) {
    try {
      if (regex.test(file)) {
        const fileName = path.parse(file).name;
        let jsonFile = fs.readFileSync(`${basePath}/build/json/${fileName}.json`);
        let metaData = JSON.parse(jsonFile);

        if(!metaData.file_url.includes('https://')) {
          await _limit()
          const url = "https://api.nftport.xyz/v0/files";
          const formData = new FormData();
          const fileStream = fs.createReadStream(`${basePath}/build/images/${file}`);
          formData.append("file", fileStream);
          const options = {
            method: "POST",
            headers: {},
            body: formData,
          };
          const response = await fetchWithRetry(url, options);
          metaData.file_url = response.ipfs_url;
          metaData.image = response.ipfs_url;

          fs.writeFileSync(
            `${basePath}/build/json/${fileName}.json`,
            JSON.stringify(metaData, null, 2)
          );
          console.log(`${response.file_name} uploaded & ${fileName}.json updated!`);
        } else {
          console.log(`${fileName} already uploaded.`);
        }

        allMetadata.push(metaData);
      }
    } catch (error) {
      console.log(`Catch: ${error}`);
    }
  }

  fs.writeFileSync(
    `${basePath}/build/json/_metadata.json`,
    JSON.stringify(allMetadata, null, 2)
  );
}

main();

> 

> 

> 

> 

- [ ] 

EDIT: My mistake was that I had not renamed the .env example file. You have to delete the example . So just .env

**Comment by deccacowen** [comment]
Where is this file?

**Comment by ShoeCrypto** [comment]
Hey guys,
i also wanted to upload th jpgs this way and it also worked on the first 35 images, but since #35 i also get that error.
My API key is saved correctly, otherwise it wouldn´t have uploaded the first 35 jpgs. Can anyone help?

**Comment by FPC00L** [comment]
im having the same issue , where would i go to delete the ".env" file ?
