### ISSUE TITLE
Im sorry if this is an obvious easy to fix problem but:

### ISSUE THREAD

**Issue by xddyyy** [HashLips/generative-art-node#18]
If i try npm run build it gives me this:

0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'run',
0 verbose cli   'build'
0 verbose cli ]
1 info using npm@7.21.0
2 info using node@v16.8.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 3ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:C:\Users\edgar\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Users\edgar\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:credentials Completed in 0ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 8ms
18 timing npm:load:configload Completed in 8ms
19 timing npm:load:setTitle Completed in 0ms
20 timing npm:load:setupLog Completed in 1ms
21 timing config:load:flatten Completed in 2ms
22 timing npm:load:cleanupLog Completed in 2ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 0ms
25 timing npm:load Completed in 15ms
26 timing command:run-script Completed in 3ms
27 verbose stack Error: Missing script: "build"
27 verbose stack
27 verbose stack To see a list of scripts, run:
27 verbose stack   npm run
27 verbose stack     at RunScript.run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:104:13)
28 verbose cwd C:\Users\edgar
29 verbose Windows_NT 10.0.19042
30 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
31 verbose node v16.8.0
32 verbose npm  v7.21.0
33 error Missing script: "build"
33 error
33 error To see a list of scripts, run:
33 error   npm run
34 verbose exit 1

thanks in advance

**Comment by cfech** [comment]
need more info, do you have a package.json that has "build" under scripts? are you in the right directory? did you run npm install already?

Says missing build script so I would check that first.

**Comment by xddyyy** [comment]
I believe so: 
This is the package.json

{
  "name": "art_generator",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "node index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Daniel Eugene Botha",
  "license": "ISC",
  "dependencies": {
    "canvas": "^2.8.0"
  }
}

I ran npm install.
Thanks for your help.

**Comment by xddyyy** [comment]
C:\Users\name\generative-art-node is my directory btw

**Comment by cfech** [comment]
https://github.com/HashLips/generative-art-node/issues/19

is your file structure similar to this issue, if on windows it usually unzips a child folder inside the parent folder so you get a weird nested folder situation which can lead to being in the wrong directory and therefore not having a build script in that directory

**Comment by xddyyy** [comment]
![tz](https://user-images.githubusercontent.com/89949848/131875527-5b366738-d36d-4791-bcb4-8d8524399600.PNG)

**Comment by cfech** [comment]
you have no node modules, have to run npm install in that directory to download the projects dependencies which are outlined in the package.json

**Comment by xddyyy** [comment]
Ok I found the error: i just had to use --prefix for it to work. Thank you for your help and sorry if I wasted your time.^^
