### ISSUE TITLE
node index.js not found

### ISSUE THREAD

**Issue by sshahbaz47** [HashLips/generative-art-node#19]
![help](https://user-images.githubusercontent.com/87954883/131765560-73929dd8-b1c9-472d-b0d0-46230295a606.PNG)

![debug issue](https://user-images.githubusercontent.com/87954883/131765931-355390f0-17be-4b54-875c-b38f0363b38f.PNG)

 Whenever I try to run "node index.js" it states cannot find module and also my package.json has a debug issue at scripts anyone else run into this problem.

I can't seem to figure out what's the problem? (I'm relatively new to coding so any help would be great)

**Comment by cfech** [comment]
Your folder structure looks odd, seems like your in the wrong directory. Should be 

C:\....\Downloads\generate-art-node-main\generate-art-node-main 

You also have 2 copies of package.json and package-log.json,  If I were you I would take that inner folder -> genertative-art-node-main 2 if you would, and move it out of your downloads, into a parent folder without the same name, make sure your only have 1 package.json and package-lock.json and then you have to run "npm install" to install the node modules (dependencies) for the project, wont work just by itself.

**Comment by sshahbaz47** [comment]
Thanks for the help :)

**Comment by divisx** [comment]
> Thanks for the help :)

Hey there, did you figure it out, im having the same issue, any help would be great:)
