### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir

### ISSUE THREAD

**Issue by manintheweb** [HashLips/generative-art-node#45]
I receive the below error when running "node index.js" from the root directory.

**Steps to recreate**
*On Windows
1. git clone https://github.com/HashLips/generative-art-node.git
2. cd generative-art-node/
3. npm install
4. npm install truffle -g
5. node index.js

### Error: ENOENT: no such file or directory, scandir
![generative-art-node-error](https://user-images.githubusercontent.com/4184130/132497873-915708ee-5d61-4660-865a-abc3d3a620c5.JPG)

**Comment by JoreisPy** [comment]
1 -don’t use windows for coding unless you use wsl
2- run npm install all
3 -no need for trufle

**Comment by manintheweb** [comment]
1. Windows is fine for coding. I've been doing it for years. But sometimes there are hiccups. I use Babun, Cmder, Bash, Zsh, etc.
2. I've done that already; it doesn't help.
3. Wrong truffle was needed. I got build errors before truffle for obvious reasons.

**Comment by manintheweb** [comment]
I solved it by changing some code in main.js. I commented out the conditional function swap for Windows and the following lines using them. I then added the code with Windows only functions. See screenshot below.

![image](https://user-images.githubusercontent.com/4184130/132609356-900aa906-a06a-4820-b6a0-3704ece6d0bf.png)

**Comment by Avegoshi** [comment]
Hi! Pls help me
![image](https://user-images.githubusercontent.com/90545915/132976590-0cd01ee9-81cd-4577-b25e-5a0c97c4a363.png)
