### ISSUE TITLE
npm install errors

### ISSUE THREAD

**Issue by CoolCowsMembership** [HashLips/generative-art-node#75]
Hello. When I run npm install I always get this large stream of errors. Help is much appreciated!

![error 1](https://user-images.githubusercontent.com/90923644/133820733-401816b4-d0a5-4cf8-8123-24e25792eabb.JPG)
![error 2](https://user-images.githubusercontent.com/90923644/133820775-5b83994f-c177-4685-ae1d-1df9516b9c1e.JPG)
![error 3](https://user-images.githubusercontent.com/90923644/133820797-b8c864e5-3ce5-439e-af9c-47feaf46ff02.JPG)

**Comment by ClaraPrograms** [comment]
Hey there CoolCowsMembership i see you closed the issue... I am struggling with the same - how did you solve it?
